# libraries needed
library(RMark)
library(tidyverse)
library(readxl)
library(BaSTA)
library(pbapply)
library(RColorBrewer)
library(grid)
library(Rmisc)
library(gss)
library(arm)
library(partR2)
library(parameters)
library(standardize)
library(colorBlindness)
library(ggthemes)
library(patchwork)

# if(!require(devtools)) install.packages("devtools")
library("devtools")
# install_github('oliviergimenez/R2ucare')
# install.packages("unmarked")
library(R2ucare)
library(unmarked)
library(marked)
